#!/bin/bash
# This file was auto-generated by /home/d3y133/nwchem-releases/nwchem-6.5/contrib/distro-tools/build_nwchem
export NWCHEM_TOP=/scratch/gpfs/kuangy/compile/Nwchem_emb/Nwchem-6.5-nlemb
export NWCHEM_TARGET=LINUX64
export NWCHEM_MODULES="all"
export NWCHEM_MPIF_WRAP=/usr/local/openmpi/1.6.3/intel130/x86_64/bin/mpif90
export NWCHEM_MPIC_WRAP=/usr/local/openmpi/1.6.3/intel130/x86_64/bin/mpicc
export NWCHEM_MPICXX_WRAP=/usr/local/openmpi/1.6.3/intel130/x86_64/bin/mpicxx
export USE_NOFSCHECK=Y
export USE_NOIO=y
export MRCC_THEORY=y
export USE_MPI=y
export USE_MPIF=y
export USE_MPIF4=y
export MPI_INCLUDE="-I/usr/local/openmpi/1.6.3/intel130/x86_64/include -I/usr/local/intel/include -I/usr/local/openmpi/1.6.3/intel130/x86_64/lib64"
export MPI_LIB="-L/usr/local/intel/lib64 -L/usr/local/intel/lib64/openmpi -L/usr/local/openmpi/1.6.3/intel130/x86_64/lib64"
export LIBMPI="-lmpi_f90 -lmpi_f77 -lmpi -ldl -lhwloc -Wl,--export-dynamic -lrt -lnsl -lutil -lhwloc"
export FC=ifort
export CC=icc
export CXX=icc
export ARMCI_NETWORK=MPI-TS
export MSG_COMMS=MPI
export BLASOPT=" -I/opt/intel/composer_xe_2013_sp1.0.080/mkl/include/intel64/ilp64/ -I/opt/intel/composer_xe_2013_sp1.0.080/mkl/include/ -lmkl_intel_ilp64 -I/usr/local/fftw/intel-13.0/3.3.3/include -L/opt/intel/composer_xe_2013_sp1.0.080/mkl/lib/intel64/ -lmkl_core -lmkl_sequential -lpthread -lm -lfftw3"
export PYTHON_EXE=/usr/bin/python
export PYTHONVERSION=2.6
export USE_PYTHON64=no
#export PYTHONPATH=/home/d3y133/Tools/lib64/python2.4/site-packages
#export PYTHONHOME=/usr
export PYTHONLIBTYPE=so

# make the symbolic link for fftw header file
ln -s /usr/local/fftw/intel-13.0/3.3.3/include/fftw3.f ./NWints/emb/fftw3.f

make clean
make nwchem_config >& config.log
make >& make.log 

#cd NWints/emb
#make
#cd ../../
#cd NWints/api
#make
#cd ../../
#cd ddscf
#make
#cd ../
#cd property
#make
#cd ../
make link
